# Bootnode Configuration for Besu Network

# Genesis configuration
genesis-file="/data/genesis.json"

# Network settings
p2p-host="0.0.0.0"
p2p-port=42007
p2p-enabled=true
discovery-enabled=true

# RPC settings
rpc-http-enabled=true
rpc-http-host="0.0.0.0"
rpc-http-port=8545
rpc-http-cors-origins=["*"]
rpc-http-api=["ADMIN", "ETH", "CLIQUE", "NET", "TRACE", "DEBUG", "TXPOOL", "PERM"]
host-allowlist=["*"]

# Logging
logging="INFO"
