services:
  nodo_eth:
    image: ethereum/client-go:v1.13.15
    container_name: geth-node
    volumes:
      - ./pwd.txt:/pwd.txt
      - ./data:/data
    ports:
      - "8545:8545"
    command: [
      "--datadir", "/data",
      "--unlock", "5be2fbdadedd293f12195dc64066356a6d58bd21",
      "--allow-insecure-unlock",
      "--mine",
      "--miner.etherbase", "5be2fbdadedd293f12195dc64066356a6d58bd21",
      "--password", "/pwd.txt",
      "--nodiscover",
      "--http",
      "--http.addr", "0.0.0.0",
      "--http.api", "admin,eth,debug,miner,net,txpool,personal,web3",
      "--http.corsdomain", "*",
      "--ipcdisable"
    ]