# Node Configuration for Besu Network

# Genesis configuration
genesis-file="/data/genesis.json"

# Network settings
p2p-host="0.0.0.0"
p2p-port=42007
p2p-enabled=true
discovery-enabled=true

# Bootnode configuration
bootnodes=["enode://4777f9487dae290408eeaa1702b1a0c0c267d143748107797baa9f07e254cea5abd89cffd4b72bf836f4797c2701f7659ac0b430c5b861a5a768f810513c1e65@192.47.0.2:42007"]

# RPC settings
rpc-http-enabled=true
rpc-http-host="0.0.0.0"
rpc-http-port=8545
rpc-http-cors-origins=["*"]
rpc-http-api=["ADMIN", "ETH", "CLIQUE", "NET", "TRACE", "DEBUG", "TXPOOL", "PERM"]
host-allowlist=["*"]

# Mining settings (for miner node)
miner-enabled=false
miner-coinbase="0x0000000000000000000000000000000000000000"

# Logging
logging="INFO"
