# Configuración del Nodo Besu: bootnode-5
# Generado automáticamente

# Configuración de datos
genesis-file="/opt/besu/genesis.json"

# Configuración de red
network-id=21359
p2p-enabled=true
p2p-host="0.0.0.0"
p2p-port=30303
max-peers=25
discovery-enabled=true

# Configuración de bootnode
bootnodes=["enode://placeholder@127.0.0.1:30303"]

# Configuración RPC
rpc-http-enabled=true
rpc-http-host="0.0.0.0"
rpc-http-port=8545
rpc-http-cors-origins=["*"]
rpc-http-api=["ETH","NET","WEB3","CLIQUE","ADMIN","DEBUG","MINER"]

# Configuración de minería
miner-enabled=true
miner-coinbase="0x9BE8C2b4c3C7c6d79F07a87F6729228786209238"
miner-stratum-enabled=false

# Configuración de sincronización
sync-mode="FULL"

# Configuración de seguridad
host-allowlist=["*"]

# Configuración de logging
logging="INFO"

